<a href="https://colab.research.google.com/github/Almattony/02-Data-Science-My-First-Scraper-Ds/blob/main/_5_universal_funksiyalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.log(arr)

<ipython-input-8-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np.log2(4)

2.0

In [ ]:
arr2 = np.random.randn(10)
arr2

array([ 1.20079521, -0.96628555,  0.5407526 ,  0.85096388, -0.33385226,
       -0.43989945, -0.52046941,  0.0202478 , -0.85542577,  0.38800079])

In [ ]:
qoldiq, butun = np.modf(arr2)
arr2

array([ 1.20079521, -0.96628555,  0.5407526 ,  0.85096388, -0.33385226,
       -0.43989945, -0.52046941,  0.0202478 , -0.85542577,  0.38800079])

In [ ]:
print(qoldiq)
print(butun)

[ 0.20079521 -0.96628555  0.5407526   0.85096388 -0.33385226 -0.43989945
 -0.52046941  0.0202478  -0.85542577  0.38800079]
[ 1. -0.  0.  0. -0. -0. -0.  0. -0.  0.]


In [ ]:
np.sign(arr2)

array([ 1., -1.,  1.,  1., -1., -1., -1.,  1., -1.,  1.])

In [ ]:
np.isnan(arr2)

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
arr2[9] = np.NaN

In [ ]:
np.isnan(arr2)

array([False, False, False, False, False, False, False, False, False,
        True])

In [ ]:
np.rint(arr2)

array([ 1., -1.,  1.,  1., -0., -0., -1.,  0., -1., nan])

In [ ]:
arr2

array([ 1.20079521, -0.96628555,  0.5407526 ,  0.85096388, -0.33385226,
       -0.43989945, -0.52046941,  0.0202478 , -0.85542577,         nan])

In [ ]:
np.abs(arr2)

array([1.20079521, 0.96628555, 0.5407526 , 0.85096388, 0.33385226,
       0.43989945, 0.52046941, 0.0202478 , 0.85542577,        nan])

In [ ]:
arr3 = np.random.randn(6)
arr4 = np.random.randn(6)
arr3

array([ 0.26828767, -0.10187113,  0.87849602,  0.86200088, -0.44894426,
        2.33989165])

In [ ]:
arr4

array([ 0.03686511,  0.60747564, -1.88304315, -0.00748757,  0.83021633,
       -1.49623685])

In [ ]:
np.add(arr3, arr4)

array([ 0.30515277,  0.50560451, -1.00454713,  0.8545133 ,  0.38127206,
        0.8436548 ])

In [ ]:
arr3 + arr4

array([ 0.30515277,  0.50560451, -1.00454713,  0.8545133 ,  0.38127206,
        0.8436548 ])

In [ ]:
np.multiply(arr3, arr4)

array([ 0.00989045, -0.06188423, -1.65424592, -0.00645429, -0.37272086,
       -3.50103212])

In [ ]:
np.maximum(arr3, arr4)

array([0.26828767, 0.60747564, 0.87849602, 0.86200088, 0.83021633,
       2.33989165])

In [ ]:
arr3


array([ 0.26828767, -0.10187113,  0.87849602,  0.86200088, -0.44894426,
        2.33989165])

In [ ]:
arr4

array([ 0.03686511,  0.60747564, -1.88304315, -0.00748757,  0.83021633,
       -1.49623685])